# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 06:02
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='imagez',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to='imagedir/'),
        ),
    ]
