# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20170830_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
