# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 18:14
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='imagez',
        ),
        migrations.AddField(
            model_name='image',
            name='images',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to='images/%s/%s/%s/%s/%s/%s/%s/%s/%s/%s/%s/%s/%s/%s/%s/%s/'),
        ),
    ]
