# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 23:35
from __future__ import unicode_literals

from django.db import migrations
import quickstart.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20170904_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='images',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to=quickstart.models.Image.generate_filename, verbose_name='Image'),
        ),
    ]
