# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_auto_20170905_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
