# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_auto_20170905_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageContainer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'image_container',
            },
        ),
        migrations.RenameField(
            model_name='image',
            old_name='images',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AddField(
            model_name='imagecontainer',
            name='images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.Image'),
        ),
    ]
