# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_auto_20170905_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecontainer',
            name='images',
        ),
        migrations.AddField(
            model_name='image',
            name='image_container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.ImageContainer'),
        ),
    ]
