# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0010_auto_20170905_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='imagecontainer',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='image',
            name='image_container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='quickstart.ImageContainer'),
        ),
    ]
